#!/usr/bin/env python3
"""Stage 1 reference oracle. The ONLY place a tokenizing or parsing library
appears in this project, and it appears on the far side of a comparison: the C
implementation is never allowed to call it, and this file is never called by the
engine.

It runs under the separate oracle environment the operator created before the
session, .venv-oracle (Python 3.12, tokenizers 0.23.2, safetensors 0.8.0,
numpy 2.5.3), and must be invoked by that explicit interpreter path. Nothing is
installed by it, here or anywhere.

EVERY ARTIFACT IS OPENED BY LOCAL PATH under models/gpt2/. No hub identifier
appears anywhere in this file, nothing is constructed by any mechanism that can
fall back to a download, and the paths actually opened are recorded in
OPENED_PATHS so a test can assert them. An oracle that fetched its own copy of
the weights would be comparing the C implementation against a different artifact
than the one on disk, and the check would silently prove nothing.

Two modes:

    emit    read the round-trip corpus fixture, produce the reference token id
            sequence for every record, and write the expected-ids fixture.

    verify  read the tensor inventory the C loader produced and compare every
            tensor -- name, dtype, shape and byte content -- against the
            reference safetensors reader, EXACTLY, reporting the first
            difference rather than a count.
"""

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
WEIGHTS_DIR = REPO / "models" / "gpt2"

TOKENIZER_JSON = WEIGHTS_DIR / "tokenizer.json"
CONFIG_JSON = WEIGHTS_DIR / "config.json"
WEIGHTS_FILE = WEIGHTS_DIR / "model.safetensors"

CORPUS = REPO / "tests" / "fixtures" / "tokenizer_roundtrip_corpus.tsv"
EXPECTED_IDS = REPO / "tests" / "fixtures" / "tokenizer_expected_ids.tsv"
INVENTORY = REPO / "src" / "gpt2_tensor_inventory.json"

# Every path this process actually opened, in order. Asserted by the test.
OPENED_PATHS = []


def _opened(path):
    OPENED_PATHS.append(str(Path(path).resolve()))
    return path


# ---------------------------------------------------------------- corpus ----

def read_corpus(path=CORPUS):
    """Returns a list of (index, class tag, bytes, label)."""
    records = []
    with open(_opened(path), "r", encoding="ascii") as fh:
        for line in fh:
            if line.startswith("#") or not line.strip("\n"):
                continue
            parts = line.rstrip("\n").split("\t")
            if len(parts) != 3:
                raise SystemExit("corpus line is not three tab-separated fields: %r" % line)
            cls, hexdata, label = parts
            records.append((len(records), cls, bytes.fromhex(hexdata), label))
    return records


# -------------------------------------------------------------- mode: emit --

NO_REFERENCE = "NO_REFERENCE"
NO_REFERENCE_REASON = (
    "the reference tokenizer accepts only str; bytes and surrogate-escaped str "
    "are both rejected with TypeError 'TextInputSequence must be str', so no "
    "reference id sequence exists for this record and none is invented"
)


def load_reference_tokenizer():
    from tokenizers import Tokenizer            # local import: oracle side only
    return Tokenizer.from_file(str(_opened(TOKENIZER_JSON)))


def emit(out_path=EXPECTED_IDS):
    tok = load_reference_tokenizer()
    records = read_corpus()

    lines = [
        "# tests/fixtures/tokenizer_expected_ids.tsv",
        "#",
        "# GENERATED by reference/stage1_oracle.py emit, from the reference",
        "# tokenizer reading models/gpt2/tokenizer.json. Committed so the C test is",
        "# self-contained under CTest. Regenerating it must reproduce this file",
        "# byte for byte -- test_stage1_oracle asserts exactly that.",
        "#",
        "# Format: tab-separated.",
        "#   1  record index, matching the corpus file line order",
        "#   2  class tag, copied from the corpus",
        "#   3  the reference token ids, comma separated, empty for an empty",
        "#      sequence, or the literal NO_REFERENCE",
        "#   4  present only for NO_REFERENCE: why no reference sequence exists",
        "#",
        "# TEST FIXTURES, not the benchmark prompt set (PERSISTENT.md 1, D3).",
    ]

    for index, cls, data, _label in records:
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError:
            lines.append("%d\t%s\t%s\t%s" % (index, cls, NO_REFERENCE, NO_REFERENCE_REASON))
            continue
        ids = tok.encode(text).ids
        lines.append("%d\t%s\t%s" % (index, cls, ",".join(str(i) for i in ids)))

    text = "\n".join(lines) + "\n"
    with open(out_path, "w", encoding="ascii", newline="\n") as fh:
        fh.write(text)
    return text


# ------------------------------------------------------------ mode: verify --

def verify_tensors():
    """Compares the committed inventory against the reference safetensors reader.

    Exact, with no tolerance: both sides read the same bytes from the same file,
    so any difference at all is a defect rather than noise. Returns (ok, message).
    """
    from safetensors import safe_open            # local import: oracle side only

    with open(_opened(INVENTORY), "r", encoding="utf-8") as fh:
        inv = json.load(fh)

    inv_tensors = {t["name"]: t for t in inv["tensors"]}

    with safe_open(str(_opened(WEIGHTS_FILE)), framework="np") as ref:
        ref_names = set(ref.keys())
        inv_names = set(inv_tensors)

        missing = sorted(ref_names - inv_names)
        if missing:
            return False, "tensor present for the reference and absent from the inventory: %s" % missing[0]
        extra = sorted(inv_names - ref_names)
        if extra:
            return False, "tensor present in the inventory and absent for the reference: %s" % extra[0]

        raw = open(_opened(WEIGHTS_FILE), "rb")
        try:
            for name in sorted(ref_names):
                entry = inv_tensors[name]
                arr = ref.get_tensor(name)

                ref_dtype = str(arr.dtype)
                want_dtype = {"F32": "float32", "F16": "float16", "BF16": "bfloat16",
                              "F64": "float64", "I64": "int64", "I32": "int32",
                              "I16": "int16", "I8": "int8", "U8": "uint8",
                              "BOOL": "bool"}.get(entry["dtype"], entry["dtype"])
                if ref_dtype != want_dtype:
                    return False, "%s: dtype %s in the inventory, %s for the reference" % (
                        name, entry["dtype"], ref_dtype)

                if list(arr.shape) != list(entry["shape"]):
                    return False, "%s: shape %s in the inventory, %s for the reference" % (
                        name, entry["shape"], list(arr.shape))

                ref_bytes = arr.tobytes()
                if len(ref_bytes) != entry["nbytes"]:
                    return False, "%s: %d bytes in the inventory, %d for the reference" % (
                        name, entry["nbytes"], len(ref_bytes))

                raw.seek(entry["file_offset"])
                got = raw.read(entry["nbytes"])
                if got != ref_bytes:
                    for i, (a, b) in enumerate(zip(got, ref_bytes)):
                        if a != b:
                            return False, ("%s: first differing byte at offset %d within the "
                                           "tensor: file has 0x%02x, the reference has 0x%02x"
                                           % (name, i, a, b))
                    return False, "%s: byte contents differ in length only" % name
        finally:
            raw.close()

    return True, "%d tensors compared, exactly, name dtype shape and every byte" % len(inv_tensors)


def verify_vocab_size():
    """The vocabulary size the reference reports against the shipped config."""
    tok = load_reference_tokenizer()
    with open(_opened(CONFIG_JSON), "r", encoding="utf-8") as fh:
        cfg = json.load(fh)
    return tok.get_vocab_size(with_added_tokens=True), cfg["vocab_size"]


# ------------------------------------------------------------------- main --

def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("mode", choices=["emit", "verify"])
    ap.add_argument("--out", default=str(EXPECTED_IDS),
                    help="emit: where to write the expected-ids fixture")
    args = ap.parse_args(argv)

    if args.mode == "emit":
        emit(args.out)
        print("wrote %s" % args.out)
        for p in OPENED_PATHS:
            print("opened %s" % p)
        return 0

    ok, message = verify_tensors()
    print("tensors: %s -- %s" % ("MATCH" if ok else "DIFFER", message))
    ref_vocab, cfg_vocab = verify_vocab_size()
    print("vocabulary: reference %d, shipped config %d -- %s"
          % (ref_vocab, cfg_vocab, "MATCH" if ref_vocab == cfg_vocab else "DIFFER"))
    for p in OPENED_PATHS:
        print("opened %s" % p)
    return 0 if (ok and ref_vocab == cfg_vocab) else 1


if __name__ == "__main__":
    sys.exit(main())
