# Regenerates git_info.h on every build so the commit hash recorded in a
# results file is the commit the binary was actually built from. The file is
# only replaced when its contents change, so this does not force a rebuild.
#
# Invoked as: cmake -DSRC_DIR=<repo> -DOUT_DIR=<generated> -P git_info.cmake

find_package(Git QUIET)

set(GIT_COMMIT "unknown")
set(GIT_DIRTY  "unknown")

if(GIT_FOUND)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD
        WORKING_DIRECTORY "${SRC_DIR}"
        OUTPUT_VARIABLE _sha
        OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE _rc
        ERROR_QUIET)
    if(_rc EQUAL 0 AND _sha)
        set(GIT_COMMIT "${_sha}")
    endif()

    execute_process(
        COMMAND "${GIT_EXECUTABLE}" status --porcelain
        WORKING_DIRECTORY "${SRC_DIR}"
        OUTPUT_VARIABLE _status
        OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE _rc2
        ERROR_QUIET)
    if(_rc2 EQUAL 0)
        if(_status STREQUAL "")
            set(GIT_DIRTY "clean")
        else()
            set(GIT_DIRTY "dirty")
        endif()
    endif()
endif()

file(WRITE "${OUT_DIR}/git_info.h.tmp"
"/* generated by scripts/git_info.cmake -- do not edit */\n"
"#ifndef BENCH_GIT_INFO_H\n"
"#define BENCH_GIT_INFO_H\n"
"#define BENCH_GIT_COMMIT \"${GIT_COMMIT}\"\n"
"#define BENCH_GIT_WORKTREE \"${GIT_DIRTY}\"\n"
"#endif\n")

execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different
                "${OUT_DIR}/git_info.h.tmp" "${OUT_DIR}/git_info.h")
file(REMOVE "${OUT_DIR}/git_info.h.tmp")
